server:
  port: 7070

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: User-Authentication
          uri: lb://User-Authentication
          predicates:
            - Path=/authentication/user/**

        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/user/interaction/**

        - id: Editor-Voice
          uri: lb://Editor-Voice
          predicates:
            - Path=/admin/editorial/**

        - id: Admin-Service
          uri: lb://Admin-Service
          predicates:
            - Path=/authentication/admin/**

        - id: NewsApp-Service
          uri: lb://NewsApp-Service
          predicates:
            - Path=/newsapp/service/**

        - id: User-Feeder
          uri: lb://User-Feeder
          predicates:
            - Path=/user/feeder/**

        - id: Top-News
          uri: lb://Top-News
          predicates:
            - Path=/api/top/**

        - id: Sports-News
          uri: lb://Sports-News
          predicates:
            - Path=/api/sports/**

        - id: Business-News
          uri: lb://Business-News
          predicates:
            - Path=/api/business/**

        - id: Search-News
          uri: lb://Search-News
          predicates:
            - Path=/api/search/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allowedHeaders:
              - Authorization
              - Content-Type